version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/app/logs:/var/log/apache2
    ports:
      - '80:80'

  db:
    hostname: db
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eatingtime
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/storage/mysql:/var/lib/mysql
      - ./docker/db/logs:/var/log/mysql